Add additional test Mailu DNS records
SeaGL/seagl-terraform pull request #27
Opened 2023-05-30 05:18 UTC by strugee

Ref SeaGL/organization#325, followup to #25

2023-05-30 17:24 UTC, AndrewKvalheim requested changes

2023-05-30 17:24 UTC, AndrewKvalheim commented on dns.tf
> +    # TODO this email doesn't seem to be created automatically
```suggestion
```

I’ve created it and shared the password.

2023-05-30 17:24 UTC, AndrewKvalheim commented on dns.tf
> +}
```suggestion
```

`dmarc@mail-test.seagl.org` isn’t [external](https://datatracker.ietf.org/doc/html/rfc7489#section-7.1) so this is redundant.

2023-05-30 17:24 UTC, AndrewKvalheim commented on dns.tf
> +    "X2VK0itMcPCBqIUvyOSIHJ8c7i8VPmcV+G6VDquepNsmFN0zcvNXAosqaWOHCnzCGzvQiwm6Lbq4vMxUsU6BLUv1JiPq3zXtqQ4tp6VynpLIy5VaF4XI5fyibsKTPuzI0d58tuiCrgCCMy5T9BmkCnQAzQIDAQAB"
```suggestion
    "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1Jw/diiAFRmarcHsr/KkGvfr22CVA5xTJTWRInvKi2My7PbWjhLSGNx7XcJw1DCcfOGb1cdArjNmYDmmG6VRRTQjCr2RWBSihIRLodnc+KPeS2Xnipi0JdNg7CTCNVQfA+znlKoWqalTT0nKrlDf87vhLmltU4wOYnrmvtZvtHkdwd9GA7hxMdHu4LnW\"\"X2VK0itMcPCBqIUvyOSIHJ8c7i8VPmcV+G6VDquepNsmFN0zcvNXAosqaWOHCnzCGzvQiwm6Lbq4vMxUsU6BLUv1JiPq3zXtqQ4tp6VynpLIy5VaF4XI5fyibsKTPuzI0d58tuiCrgCCMy5T9BmkCnQAzQIDAQAB"
```

[This](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record.html#records) is ridiculous.

2023-05-30 17:32 UTC, AndrewKvalheim commented on dns.tf
Did you mean to omit the TLSA record?

2023-05-30 18:11 UTC, strugee commented on dns.tf
Yes. Route 53 doesn't support TLSA records but honestly I'm not fussed because TLSA is of questionable value anyway - it requires DNSSEC to mean anything, but DNSSEC is highly organizationally centralized and requires trusting entities you may not trust _forever_. https://youtu.be/UawS3_iuHoA?t=1747 for more if you're curious.

2023-05-30 19:50 UTC, AndrewKvalheim commented on dns.tf
Ah thanks. I’d only gotten as far as opening a couple tabs about TLSA and then stepped away.

2023-06-08 16:14 UTC, sntxrr reviewed
Looks good overall, let's dial it in and merge it!

2023-06-21 04:09 UTC, strugee commented on dns.tf
> +}
Ah nice catch - I just blindly transcribed.

2023-06-21 04:12 UTC, strugee commented on dns.tf
> +    "X2VK0itMcPCBqIUvyOSIHJ8c7i8VPmcV+G6VDquepNsmFN0zcvNXAosqaWOHCnzCGzvQiwm6Lbq4vMxUsU6BLUv1JiPq3zXtqQ4tp6VynpLIy5VaF4XI5fyibsKTPuzI0d58tuiCrgCCMy5T9BmkCnQAzQIDAQAB"
I forgot about this, omg. It's not Terraform's fault, this is a Route 53 thing

2023-06-21 19:49 UTC, AndrewKvalheim approved these changes

2023-06-21 22:56 UTC, merged